-- Active: 1659109364264@@127.0.0.1@3306@mavdb
-- CREATE DATABASE
CREATE DATABASE DEMODBMAV;
-- SWITCH TO DATABASE
USE DEMODBMAV;
-- REMOVE DATABASE
DROP DATABASE DEMODBMAV;


USE MAVDB;
-- DDL STATEMENTS
-- CONSTRAINTS / PRIMARY KEY - NO NULL VALUES OR DUPLICATES ALLOWED
DROP TABLE AUTHOR;
CREATE TABLE AUTHOR (
AUTHOR_ID INT NOT NULL PRIMARY KEY ,
AUTHOR_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NULL
);

DROP TABLE BOOK;
CREATE TABLE BOOK(
BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
BOOK_NAME VARCHAR(50) NOT NULL,
AUTHOR_ID INT ,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);

-- DML STATEMENTS
-- INSERT RECORDS
INSERT INTO AUTHOR VALUES (1, 'SIMON SINEK','MEXICO CITY');
-- COLUMN COUNT MATCH MISMATCH
INSERT INTO AUTHOR VALUES (5, 'SIMON SINEK');
SELECT * FROM AUTHOR;
-- INSERTS ARE ATOMIC / ENTIRE ROW GETS INSERTED OR NOTHING GETS INSERTED.
-- INSERT ALL VALUES

INSERT INTO AUTHOR VALUES (1, 'HECTOR GARCIA','TOKYO');
-- INSERT PARTIAL VALUES
INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES (3, 'RYAN HOLIDAY');
INSERT INTO AUTHOR VALUES (4, 'RYAN HOLIDAY', NULL);
INSERT INTO AUTHOR VALUES (5, 'ROBIN  SHARMA', NULL);
INSERT INTO AUTHOR VALUES (6, 'J K ROWLING', NULL);
USE MAVDB;
-- WRONG
SELECT * FROM AUTHOR WHERE CITY = NULL;
SELECT * FROM AUTHOR WHERE CITY != NULL;
SELECT * FROM AUTHOR WHERE CITY IS NULL;
SELECT * FROM AUTHOR WHERE CITY IS NOT NULL;
SELECT * FROM AUTHOR WHERE NOT  CITY IS NULL;

SELECT * FROM AUTHOR WHERE NOT CITY IS NOT NULL;
-- TEST NULL FOR PRIMARY KEY
-- AUTHOR_ID CANNOT BE NULL
INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES (NULL, 'RYAN HOLIDAY');
-- AUTHOR_NAME CANNOT BE NULL
INSERT INTO AUTHOR (AUTHOR_ID, CITY) VALUES (7, 'NEW YORK');
-- UPDATE RECORD
UPDATE AUTHOR SET CITY = 'MIAMI' WHERE AUTHOR_ID = 4;
-- DELETE RECORD
DELETE FROM AUTHOR WHERE AUTHOR_ID = 3;

SELECT * FROM BOOK;
INSERT INTO BOOK (BOOK_NAME,AUTHOR_ID) VALUES ('START WITH WHY', 1);
SELECT * FROM BOOK;
INSERT INTO BOOK (BOOK_NAME,AUTHOR_ID) VALUES ('START WITH WHY', 1);
-- FOREIGN KEY CONSTRAINT VIOLATION
INSERT INTO BOOK (BOOK_NAME,AUTHOR_ID) VALUES ('THE DAILY STOIC', 5O);
-- ALLOWS NULLS
INSERT INTO BOOK (BOOK_NAME) VALUES ('THE DAILY STOIC');
INSERT INTO BOOK (BOOK_NAME) VALUES ('DEEP WORK');
INSERT INTO BOOK (BOOK_ID, BOOK_NAME) VALUES (2,"MAN'S SEARCH FOR MEANING");

-- COMPOSITE PRIMARY KEY
-- DUPLICATE FIRST NAME & LAST NAME, BUT FIRST NAME + LAST NAME IS UNIQUE
CREATE TABLE EMPLOYEE (
FNAME CHAR(10),
LNAME CHAR(10),
CITY CHAR(20),
PRIMARY KEY (FNAME, LNAME)
);
SELECT * FROM EMPLOYEE;
-- SAM + PETER
INSERT INTO EMPLOYEE VALUES ('SAM', 'PETER', 'MUMBAI'); 
INSERT INTO EMPLOYEE VALUES ('SAM', 'JOHN', 'MUMBAI'); 
INSERT INTO EMPLOYEE VALUES ('ELTON', 'JOHN', 'MUMBAI');
-- DUPLICATE COMPOSITE KEY 
INSERT INTO EMPLOYEE VALUES ('SAM', 'JOHN', 'CHENNAI'); 

-- COMPOSITE FOREIGN KEY
CREATE TABLE EMPLOYEEHOBBY (
-- HOBBYID INT PRIMARY KEY, 
FNAME CHAR(10),
LNAME CHAR(10),
HOBBY CHAR(20),
FOREIGN KEY (FNAME, LNAME) REFERENCES EMPLOYEE(FNAME, LNAME)
);
SELECT * FROM EMPLOYEEHOBBY;
INSERT INTO EMPLOYEEHOBBY VALUES ('SAM', 'PETER', 'CRICKET'); 
INSERT INTO EMPLOYEEHOBBY VALUES ('SAM', 'BILL', 'GOLF'); 
INSERT INTO EMPLOYEEHOBBY VALUES ('ELTON', 'JOHN', 'MUSIC'); 
INSERT INTO EMPLOYEEHOBBY VALUES ('BILLY', 'JOHN', 'SKYDIVE'); 


DROP TABLE TEST;
CREATE TABLE TEST(TESTID INT);
-- ALTER TABLE COMMAND
ALTER TABLE TEST
MODIFY COLUMN TESTID VARCHAR(10);
SELECT SYSDATE();
SELECT DAYOFMONTH(SYSDATE());
SELECT DAYNAME(SYSDATE());

USE SAKILA;
SELECT * FROM ACTOR;